image: alpine:latest
pages:
  stage: deploy
  before_script:
  - apk update && apk add brotli
  script:
  - gzip -9 -f -k */*.htm */*.html
  - brotli -f -k */*.htm */*.html
  - mkdir .public
  - mv -t .public *
  - mv .public public
  artifacts:
    paths:
    - public
    expire_in: 1 day
  only:
  - master
